### ISSUE TITLE
Revisión arquitectura

### ISSUE THREAD

**Issue by HugoLebredo** [Arquisoft/viade_es1a#28]
Buenas noches equipo. Os paso un resumen de lo hablado en clase. Algunas cosas son genéricas y otros aspectos concretos de vuestro trabajo.

**Primeras consideraciones:**

- Ya se os ha dicho un par de veces veces e insisto. **Ser 4 personas no es un inconveniente**, todo lo contrario. Si os organizáis bien podéis ser mucho más eficientes y rápidos. Para eso es fundamental pensar como profesionales

1. Preparar las reuniones, que quede claro quien hace que y fechas de entrega.
2. Pedir ayuda si algo no sale o **incluso si no gusta**, está en vuestra mano reorganizar tareas en el grupo y evitar quemaros. Además de esta manera el grupo se toma la temperatura.
3. Un equipo compacto es siempre un reto.

- El escribir la documentación en español es una decisión (yo creo que buena en vuestra situación). Cualquier decisión implica sacrificar algo. Rapidez vs fiabilidad por poner un ejemplo. En este caso perdeis valor añadido (la informática es un mundo en ingles) pero ganáis agilidad y rapidez (cosa que os conviene).

- esto es una carrera ciclista, no hay que perder el tiempo mirando a los lados o atrás. Hay que poner foco en los objetivos, y no perderlos de vista :checkered_flag:                       :bicyclist:

- [x] **1.2 Quality Goals:** Sugerencia; podéis valorar la importancia de cada objetivo. Si lo hacéis indicad en un texto como interpretarlo. Por ejemplo si escribís  _1. Usabilidad_ el1 ¿es lo más importante o menos?

- [x]  **1.3 Stakeholders:** Los perfiles tienen que ser más precisos. Es más adecuado que User utilizar palabras que definan los diferentes tipos de usuario como por ejemplo _Senderista_. Parece un  copy paste del proyecto del año pasado. Esforzaros en estos detalles, dan calidad a la documentación

- [x] **2. Architecture Constrains:** Hay que distinguir las restricciones de las decisiones.

- Una _restricción_ viene impuesta por factores externos al grupo (Por ejemplo la utilización de PODs).
- Una _decisión_ por el contrario se ha elegido por el grupo. Por ejemplo RC3 es una decisión del grupo. (Os lo he dicho también en las consideraciones previas :wink:) revisadlas

-  El haber codificado las restricciones me ha gustado y la codificación también letras y cifras. 👍

- [x] **3.1 Business Context:** Fatal. En los diagramas tenéis que trabajar. Este diagrama de contexto es una representación general que muestra muy por encima lo que va a hacer vuestro proyecto. Tiene que mostrar los actores así como otros componentes. Echadle un vistazo a la documentación de clase o Google. Son sencillos pero tenéis que pillar la idea.

**Todos los gráficos deben tener leyenda, 2 flechas y resto de cosas que se explicaron en la práctica anterior**

- [x]  **4 Solution Strategy:** Si tenéis  TO DO hay que pasarlos a issues.

- [x]  **Puntos 5 a 8** Tenéis que empezar a hacer foco en estos puntos. Es normal en el estado de madurez del proyecto que no existan estos esquemas. Pero recordad que cuando empecéis a programar no dejar esto descuidado porque al final es mucho trabajo para poco tiempo. ⏰ La metodología requiere constancia.

Si necesitáis refuerzo en UML repasad los siguientes diagramas. En las transparencias de la práctica 3 tenéis una breve descripción a partir de ahí mirad más doc de otras asignaturas y Google. En 2 tardes los habréis dominado.

- Clases
- Despliegue
- Secuencia
- Componentes

- [x] **9 Design Decisions:** Recomendación, incluir una tabla con la siguiente estructura _Fecha, Decisión tomada, Nombre Participantes, Pros, Contras_

- Incluir las decisiones a las que me referí en el apartado 2

- [x] **10.2 Quality Scenarios:** Añadir en la tabla una columna con un _identificador de incidencia_, Al igual que en apartados anteriores. Es mucho más elegante.

En los escenarios no utilices descripciones genéricas. Tenéis que ser concretos.

- "Tiempos de respuesta breves" ❌
- "Tiempos de respuesta menores de 3 milisegundos ✅

- [x] **11 Risk and Terchnical Debts:** En clase hemos hablado de incluir la _deuda técnica_ -Todos los atajos tomados que después deberán solucionarse- Ejemplo: "Hemos incluido todo el código en un único script de manera desordenada para cumplir las fechas de entrega. El código de reordenará de forma pulcra".

- Fusionar las tablas riesgos + soluciones . Que se pueda ver la solución de cada riesgo a su lado. Es una buena manera de mantener la documentación ordenada. La finalidad de la documentación es que un tercero pueda entender el proyecto. Tened eso en cuenta.

- [x] **12 Glosary** Ampliadlo con los acrónimos que vayan surgiendo. Haceos la siguiente pregunta ¿Entendería este término si acabaran de asignarme a este proyecto?

**Plan de acción:**
1. Tenéis que poneros a estudiar los diagramas. Se pillan rápido pero eso **hoy mismo.** El viernes deben estar controlados. Si no entendéis los diagramas, no podreis trasladarlos a la plantilla. Comenzareis a programar sin un plan porque vais pillaos  y en un mes vuestro código no se adecuará a la documentación ficticia que tratareis de parchear. :skull: Es mejor poner orden ahora, coger perspectiva y después velocidad.

2. Todas las estructuras de tablas tienen que estar hechas esta semana, rellenarlas será más rápido.

3. Los diagramas en papel. **Aprended a hacerlos bien**, cuando lo tengáis claro ya le dareis un lavado de cara.

**Conclusiones:**
Vais pillados pero esta situación se puede revertir. Eso si, esto depende de vosotros. Si os sentis paralizados porque son muchas cosas o teneis miedo es normal. A todos nos pasa con las cosas nuevas. La cuestión es la actitud con la que nos enfrentamos a estas situaciones. Intentad disfrutar dentro de lo posible y trabajad.

Mucho ánimo! :muscle:

**Comment by samuelmorenov** [comment]
Detalle de puntos que quedan por hacer y no han sido concretados arriba:
- [ ] **5 Vista del bloque de consturccion:** Hay que hacer los diagramas de los distintos niveles, de manera que en cada nivel se muestre con mas detalle cual es la composición de cada elemento. 
- [ ] **6 Vista de tiempo de ejecución:** Hay que hacer una vista por cada escenario:
- [ ] 6.1 Vista de almacenar rutas.
- [ ] 6.2 Visualizar en el mapa.
- [ ] 6.3 Compartir archivos.
- [ ] 6.4 Ver notificaciones.
- [ ] 6.5 Compartir con grupos.
- [ ] **7 Vista de implementación:** Hay que explicar como se desplegará la aplicación, contemplando las opciones de texting y docker
- [ ] **11 Riesgos y deudas tecnicas** Quitar los riesgos que no lo son, añadir las deudas tecnicas que aun no se han solucionado y estan en las issues
